version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: project_test
      cache_from:
        - project/project:app
    image: project/project:app
    env_file:
      - docker.test.env
  worker:
    image: project/project:app
    env_file:
      - docker.test.env
