version: "3.8"
services:
  gems:
    image: busybox
    volumes:
      - /project_gems
  postgres:
    image: postgres:12.3-alpine
    volumes:
      - project_postgres:/var/lib/postgresql/data
  redis:
    image: redis:5.0.9-alpine
  mailer:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: project_development
    image: project_app
    command: ./docker-entrypoint.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/project
      - project_gems:/project_gems
    stdin_open: true
    tty: true
    depends_on:
      - webpacker
      - postgres
      - redis
      - gems
    env_file:
      - docker.env
  webpacker:
    image: project_app:latest
    command: ./bin/webpack-dev-server
    ports:
      - "3035:3035"
    volumes:
      - .:/project
      - project_gems:/project_gems
    env_file:
      - docker.env
  worker:
    image: project_app:latest
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/project
      - project_gems:/project_gems
    env_file:
      - docker.env
volumes:
  project_gems:
  project_postgres:
